# Site wide configuration

title: "Richarizardd"
description: "Junior undergraduate at Johns Hopkins University."
logo: site-logo.png
teaser: default-teaser.png
locale: en_US
url: https://richarizardd.github.io


# Jekyll configuration

permalink: /:categories/:title/
lsi: true
markdown: kramdown
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap
  - jekyll-archives
include: [".htaccess"]
exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "node_modules", "Gruntfile.js", "package.json", ".jekyll-assets-cache"]


# Plugin: jekyll-assets

assets:
  sources:
    - _assets/javascripts
    - _assets/stylesheets
  baseurl: https://richarizardd.github.io/assets/
  js_compressor: uglifier
  css_compressor: sass
  cachebust: hard
  cache: true
  debug: false
  version: 1


# Plugin: jekyll-archives

jekyll-archives:
  enabled:
    - tags
    - year
  layouts:
    year: year_index
    tag: tag_index
  permalinks:
    year: /:year/
    tag: /tag/:name/


# Site owner

owner:
  name: "Richard Chen"
  email: rchen40@jhu.edu 
  facebook: RichardChen.95
  instagram: RichardChen95
  github: richarizardd
  bing:
    verify: D81F4C18A6CB3018F64D7C827D953DFD
  alexa:
    verify: Y5DYjZ4VWlrQzBP5kcQJeOKLNas
  yandex:
    verify: 55a5419baf76a498
  bio: "No such thing as a free lunch."
  avatar: bio-photo-richard.jpg # 160x160 px image for author byline
disqus-shortname: Richarizardd


# Collections

collections:
  faqs:
    output: true
    permalink: /:collection/:path/
    title: FAQs
  components:
    output: false
  colors:
    output: false
